[mongodb]
mongodb-dev.daws88s.quest

[catalogue]
catalogue-dev.daws88s.quest

[redis]
redis-dev.daws88s.quest

[user]
user-dev.daws88s.quest

[cart]
cart-dev.daws88s.quest

[mysql]
mysql-dev.daws88s.quest

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.daws88s.quest
CATALOGUE_HOST=catalogue-dev.daws88s.quest
REDIS_HOST=redis-dev.daws88s.quest
USER_HOST=user-dev.daws88s.quest
CART_HOST=cart-dev.daws88s.quest
MYSQL_HOST=mysql-dev.daws88s.quest

