- name: configure rabbitmq server
  hosts: rabbitmq
  become: yes

  tasks:
    - name: copy rabbitmq repo file
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: enable rabbitmq management plugin
      ansible.builtin.command: rabbitmq-plugins enable rabbitmq_management

    - name: start and enable rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: RoboShop@1
        state: present
        tags: administrator