# ansible-playbook -i localhost, -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}' roboshop.yaml
- name: create ec2 and r53 records
  hosts: localhost
  connection: local

  vars:
    sg_id: sg-0151d436ba995ac46
    ami_id: ami-0220d79f3f480ecf5
    domain_name: daws88s.space
    env: dev
    task_action: create

  tasks:
    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"
      when: task_action == "create"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: false
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: task_action == "create"

    - name: create r53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: false
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when:
        - item.item == "frontend"
        - task_action == "create"