# ansible-playbook -i localhost,   -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}'  -e action=destroy roboshop.yaml
- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    image_id: ami-03265a0778a880afb
    instance_type: t2.micro
    security_group: sg-0eebe34cb6d5145f7
    zone: daws88s.space

  tasks:

  - name: CREATE EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ image_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      wait: yes
    loop: "{{ instances }}"
    register: ec2_output
    when: state == "present"

  - name: PRINT EC2 OUTPUT
    debug:
      msg: "{{ ec2_output }}"
    when: state == "present"

  - name: CREATE Route53 records
    amazon.aws.route53:
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      state: present
    loop: "{{ ec2_output.results }}"
    when: state == "present"

  # ---------------- DESTROY ---------------- #

  - name: TERMINATE EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      state: absent
    loop: "{{ instances }}"
    when: state == "absent"

  - name: DELETE Route53 records
    amazon.aws.route53:
      zone: "{{ zone }}"
      record: "{{ item }}.{{ zone }}"
      type: A
      state: absent
    loop: "{{ instances }}"
    when: state == "absent"